Implemented Moving Tower Placement Areas
DishonJordan/TowerDefenseTutorial pull request #1
Opened 2019-04-25 16:07 UTC by DishonJordan

Integrated both linear movement between two points and a 3-point L shaped movement of towers.

2019-04-25 18:00 UTC, bi3mer requested changes
`LinearTowerMovement` and `MultiPointMovement` are almost exactly the same and contain some duplicate code. Make these a single class or create a base which both inherit from to reduce duplicate code. 

I've stopped putting notes on your comments, but most of them aren't really serving a purpose. Unless the code is doing something complicated or unintuitive, you don't need a comment. With that said, function comments are usually nice but not necessary the majority of the time.

[https://docs.microsoft.com/en-us/style-guide/welcome/](https://docs.microsoft.com/en-us/style-guide/welcome/) make sure to go over the style guide.

I'm stopping a bit early since a lot of my comments are repeats of past comments. Take a look and make updates to the scripts that you updated. Do not do this for the whole repository just the scripts that you have modified for this pull request. 

Minus style stuff, it's looking pretty good. Nice Job. Also, [this](https://tstavropoulos.github.io/blargs/git_submodules.html) isn't related to your project but make sure to read it before we meet for what you will be working on.

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +    //Tower movement speed
I don't think that this comment really helps us

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +    int segment;
I'd rather this variable's name be a bit more descriptive and remove the comment. Also you need to define whether this is public or private

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +    //Tower movement speed
Instead of using public you can use [https://docs.unity3d.com/ScriptReference/SerializeField.html](https://docs.unity3d.com/ScriptReference/SerializeField.html) to make this variable private and protect it from outsiders. Unless you have a very good reason, you should never make a variable public.

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +    public Vector3[] points = new Vector3[2];
just name this `orderedPoints` or something and remove the comment. Also make it private or do something to protect it

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +    // Start is called before the first frame update
comment doesn't do anything for us.

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +            segment = (segment == 1) ? 0 : segment + 1;
The if statement needs brackets around it and you should remove the ternary statement. Ternary statements, while convenient, are awful to read.

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/LinearTowerMovement.cs
> +
this new line isn't helping us

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +    //Tower movement speed
remove

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +    public float speed;
private

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +    //Defines that part of the traversal we are on
remove this

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +    //Holds an ordered set of points to be traversed
remove this

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +
new line isn't helping us

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +
new line isn't helping us

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +    // Update is called once per frame
comment doesn't improve clarity of code, remove

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +    // Start is called before the first frame update
comment doesn't improve clarity of code, remove

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +
bad new line

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Movement/MultiPointMovement.cs
> +            segment = (segment == 3) ? 0 : segment + 1;
same thing about brackets and ternary statement

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        bool m_IsOccupied;
set whether this i s public or not and change the variable to either isOccupied or IsOccupied depending on whether or not it is public.

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        PlacementTile m_SpawnedTile;
remove the m_ and set to public or private

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public PlacementTile placementTilePrefabMobile;
should start with a capital if public

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public PlacementTile placementTilePrefab;
does this have to be public?

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public PlacementTile placementTilePrefabMobile;
does this have to be public?

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Transform start_position;
snake case isn't in the style guide for c#. also does it have to be public?

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Transform middle_position;
snake case isn't in the style guide for c#. also does it have to be public?

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Transform end_position;
snake case isn't in the style guide for c#. also does it have to be public?

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +            return m_IsOccupied ? TowerFitStatus.Overlaps : TowerFitStatus.Fits;
remove ternary operator

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public bool isMovable()
```c#
public bool Movable() => true;
```

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public string getMovementScriptName()
g Must be capital

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Vector3 getStartVector()
g Must be capital

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Vector3 getMiddleVector()
https://tstavropoulos.github.io/blargs/git_submodules.html

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public float getSpeed()
https://tstavropoulos.github.io/blargs/git_submodules.html

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Vector3 getEndVector()
https://tstavropoulos.github.io/blargs/git_submodules.html

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +
Only 1 new line not 2

2019-04-25 18:00 UTC, bi3mer commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +
bad new lines

2019-05-05 05:41 UTC, DishonJordan commented on Assets/Scripts/TowerDefense/Towers/Placement/LTowerPlacementArea.cs
> +        public Transform start_position;
Fixed the snake casing. It does need to be public because it is accessed from the Tower.cs script

2019-05-09 06:49 UTC, merged